### ISSUE TITLE
libvte-2.90-dev is no longer in ubuntu, only libvte-2.91-dev is

### ISSUE THREAD

**Issue by OvermindDL1** [oakes/SolidOak#53]
`libvte-2.90-dev` is no longer in Ubuntu, only `libvte-2.91-dev` is, and compile fails due to mismatched version:

```
--- stderr
thread '<main>' panicked at '`"pkg-config" "--libs" "--cflags" "vte-2.90"` did not exit successfully: exit code: 1
--- stderr
```

Needs updating.

**Comment by oakes** [comment]
Fixed in README

**Comment by OvermindDL1** [comment]
Does not appear to be resolved.  I just recloned it, the readme does indeed state to get vte-2.91, however the project still fails with:
```rust
--- stderr
thread '<main>' panicked at '`"pkg-config" "--libs" "--cflags" "vte-2.90"` did not exit successfully: exit code: 1
--- stderr
Package vte-2.90 was not found in the pkg-config search path.
Perhaps you should add the directory containing `vte-2.90.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vte-2.90' found
```

So the project is still trying to use vte-2.90, not 2.91, so now the readme does not match what the source is wanting?

**Comment by oakes** [comment]
Sorry I was still working on the code when I wrote that comment. I just pushed a new commit to this project with the new deps that you need. Please pull that, do an update, and let me know if the build works for 2.91 now.

**Comment by OvermindDL1** [comment]
Lol, all good, trying compile now, and successful compile!  I do not have a GUI available right at this moment so will give it a try this evening when I get home and if any further issues then I will open a new issue.  But launching it in a virtual framebuffer did load it without issue at least, so its looks good.  Thanks much!  :-)

**Comment by oakes** [comment]
Awesome! Yeah please open a new issue if you notice anything.
